name: lrs2sky
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - astropy
  - matplotlib
  - photutils
  - pyyaml
  - pandas
  - pytables
  - pip
  - pip:
      - -e .
